### ISSUE TITLE
Deploy node with PoA-consensus

### ISSUE THREAD

**Issue by ChronosXYZ** [MoonSHRD/Project-issues#33]

**Comment by JackBekket** [comment]
https://github.com/MoonSHRD/MS-Factory/blob/deploy/cloud-testnet-deploy/note.md

**Comment by JackBekket** [comment]
https://hackernoon.com/setup-your-own-private-proof-of-authority-ethereum-network-with-geth-9a0a3750cda8

**Comment by JackBekket** [comment]
51.15.244.238
